branches:
  only:
    - master

sudo: required

language: python

services:
  - docker

before_script:
  - python --version
  - docker version
  - docker ps -a
  - docker build -t clarencep/php7-custom-build-from-zero:$TRAVIS_BRANCH .
  - docker images
  - docker ps -a

script:
  - docker run -it --rm clarencep/php7-custom-build-from-zero:$TRAVIS_BRANCH sh -cxe "php -v && php -m && php -i"